
package analizador.gui;



import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import analizador.logica.Logica;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import analizador.logica.TextLineNumber;
import java.awt.Color;


/**
 *Interfaz del Analizador lexico
 * @author CJuanGO
 */
public class Ventana extends javax.swing.JFrame {

  
    private final Logica logica;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        logica = new Logica();
        initComponents();
         setLocationRelativeTo(this);
         TextLineNumber tln = new TextLineNumber(txaCodigo);
         jScrollPane2.setRowHeaderView(tln);
         
                  }
     //Ruta Archivo
    String rutaArchivo = "";
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtAreaErrores = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaCodigo = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabelGuardado = new javax.swing.JLabel();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonAnalizar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTxtAreaMensajes = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivo = new javax.swing.JMenu();
        jMenuItemAbrir = new javax.swing.JMenuItem();
        jMenuGuardar = new javax.swing.JMenuItem();
        jMenuGuardarComo = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenuItem2.setText("jMenuItem2");

        jMenu5.setText("jMenu5");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(780, 425));
        setMinimumSize(new java.awt.Dimension(780, 425));
        setPreferredSize(new java.awt.Dimension(780, 425));
        setResizable(false);
        setSize(new java.awt.Dimension(780, 425));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTxtAreaErrores.setColumns(20);
        jTxtAreaErrores.setRows(5);
        jScrollPane1.setViewportView(jTxtAreaErrores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 310, -1));

        txaCodigo.setBorder(null);
        txaCodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txaCodigo.setCaretColor(new java.awt.Color(204, 204, 204));
        txaCodigo.setSelectionColor(new java.awt.Color(153, 255, 255));
        jScrollPane2.setViewportView(txaCodigo);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 430, 280));

        tabla.setAutoCreateRowSorter(true);
        tabla.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lexema", "Token", "Linea"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane4.setViewportView(tabla);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 308, 220));

        jLabel1.setText("Errores");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 100, 30));
        getContentPane().add(jLabelGuardado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 562, -1, -1));

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 220, 30));

        jButtonAnalizar.setText("Analizar");
        jButtonAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnalizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAnalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 210, 30));

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTxtAreaMensajes.setColumns(2);
        jTxtAreaMensajes.setRows(5);
        jScrollPane3.setViewportView(jTxtAreaMensajes);
        jTxtAreaMensajes.getAccessibleContext().setAccessibleParent(tabla);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 430, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/analizador/resources/37029wide.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 400));

        jMenuBar1.setBorder(null);
        jMenuBar1.setBorderPainted(false);

        archivo.setText("Archivo");

        jMenuItemAbrir.setText("Abrir Archivo");
        jMenuItemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAbrirActionPerformed(evt);
            }
        });
        archivo.add(jMenuItemAbrir);

        jMenuGuardar.setText("Guardar");
        jMenuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGuardarActionPerformed(evt);
            }
        });
        archivo.add(jMenuGuardar);

        jMenuGuardarComo.setText("Guardar Como");
        jMenuGuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGuardarComoActionPerformed(evt);
            }
        });
        archivo.add(jMenuGuardarComo);

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        archivo.add(jMenuSalir);

        jMenuBar1.add(archivo);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
  System.exit(0);
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenuGuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGuardarComoActionPerformed
      boolean variable = logica.guardarComo(txaCodigo.getText());
        if (variable == true) {
            if(jTxtAreaErrores.getText().equals("Error al guardar: \n debe guardar primero en Guardar como")){
                jTxtAreaErrores.setText("");
            }
            jMenuGuardarComo.setEnabled(true);
                    }
    }//GEN-LAST:event_jMenuGuardarComoActionPerformed

    private void jMenuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGuardarActionPerformed
          boolean mirar= logica.guardar(txaCodigo.getText());
          if(mirar){
              jTxtAreaMensajes.setCaretColor(Color.green);
              jTxtAreaMensajes.setText("Guardado");
               jTxtAreaErrores.setText("");
          }else{
              jTxtAreaErrores.setText("Error al guardar: \n debe guardar primero en Guardar como");
          }
              
    }//GEN-LAST:event_jMenuGuardarActionPerformed

    private void jMenuItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAbrirActionPerformed
       boolean estado= logica.abrirArchivo();
        if(estado==true){
            jMenuGuardarComo.setEnabled(true);
             jTxtAreaErrores.setText("");
             jTxtAreaMensajes.setText("");
        }
    }//GEN-LAST:event_jMenuItemAbrirActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
       
                     txaCodigo.setText("");    
                 limpiarTabla();
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnalizarActionPerformed
          if (logica.getRutaArchivo() == null) {
               jTxtAreaErrores.setText("Error al analizar: \n No se ha guardado el archivo \n Primero debe guardar el archivo y luego analizar");
              
        } else if(txaCodigo.getText().equals("")){
            jTxtAreaErrores.setText("No hay codigo Para Analizar \n Por favor Escriba su codigo");
            
        }else {
           logica.guardar(txaCodigo.getText());
           jTxtAreaErrores.setText("");
           jTxtAreaMensajes.setText("Guardado");
            limpiarTabla();
            logica.getTokens().clear();
           logica.obtenerTokens(txaCodigo.getText(), 1);
        }
    }//GEN-LAST:event_jButtonAnalizarActionPerformed
    /**
     * Metodo que lanza la aplicacion
     *
     * @param args the command line arguments
     */
   
      public static void main(String args[]) {
        // Establece el look and fell
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //Genera una llamada de la interfaz principal
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
                
            }
        });
    }
      
      
      /**
     * Método utilizado para remover todos los elementos de la tabla de la
     * interfaz principal
     */
    public void limpiarTabla() {
        DefaultTableModel limpiar = (DefaultTableModel) tabla.getModel();
        int rowCount = limpiar.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            limpiar.removeRow(i);
        }
        tabla.setModel(limpiar);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu archivo;
    private javax.swing.JButton jButtonAnalizar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelGuardado;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuGuardar;
    private javax.swing.JMenuItem jMenuGuardarComo;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemAbrir;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public static javax.swing.JTextArea jTxtAreaErrores;
    public static javax.swing.JTextArea jTxtAreaMensajes;
    public static javax.swing.JTable tabla;
    public static javax.swing.JTextPane txaCodigo;
    // End of variables declaration//GEN-END:variables

     



}
