
package analizador.crearTokens;

/**
 *Clase que contiene los tokens del lenguaje
 * @author CJuanGO
 */
public enum Tokens {
COMENTARIO, PALABRA_RESERVADA,IDENTIFICADOR,SEPARADOR,TERMINAL_DE_LINEA,
ABRIR_LLAVE, CERRAR_LLAVE, ABRIR_CORCHETE, CERRAR_CORCHETE, ASIGNACION, OPERADOR_ARITMETICO, OPERADOR_RELACIONAL,
OPERADOR_LOGICO, CADENA,CONCATENACION


}
